# Generated by Django 5.2.5 on 2025-09-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_alter_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Cliente'), (1, 'Profissional')], default=0, verbose_name='Tipo de usuário'),
        ),
    ]
