# Generated by Django 5.2.6 on 2025-09-12 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Está excluido?')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True, verbose_name='Data/Horário Agendado')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Mensagem')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('rejected', 'Recusado')], default='pending', max_length=20, verbose_name='Status')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requests', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='jobs.job', verbose_name='Serviço')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requests_received', to=settings.AUTH_USER_MODEL, verbose_name='Profissional')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['professional', 'status'], name='jobrequests_profess_5614cf_idx'), models.Index(fields=['scheduled_date'], name='jobrequests_schedul_3ba50d_idx')],
            },
        ),
    ]
