# Generated by Django 5.2.5 on 2025-09-14 17:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_professional'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Está excluido?'),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
